USE UNIVERSITY;

DELIMITER $$
CREATE TRIGGER `finish_after_confirm`
  AFTER UPDATE ON TRADE
  FOR EACH ROW 
BEGIN
  UPDATE SELLING SET FINISHED=true
  WHERE SellingID = OLD.SellingID;
  UPDATE TRADE SET FINISHED=true
  WHERE SellingID = OLD.SellingID;  
END$$
DELIMITER ;